name: CI Pipeline with 3 jobs

on:
  push:
    branches: [main]
  pull_request:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Bash script
        run: bash -n status-check.sh

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - name: Run simulated tests
        run: echo "✅ Running tests..."

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "::warning::Caution with this step"
      - run: echo "::error::Simulated error"
      - run: echo "::notice::This is just an informational message"
      - uses: actions/checkout@v4
      - name: Generate artifact
        run: zip report.zip status-check.sh
      - name: Upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
      - name: Summary
        run: |
          echo "### ✅ CI Finished" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- [Download artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> GITHUB_STEP_SUMMARY