name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://appmonitor.com
    steps:
      - run: echo "🛸 Deploying to ${{ vars.PROD_DOMAIN }}"