name: Run Monitor

on: [workflow_dispatch]

jobs:
  use-env:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ vars.APP_ENV }}
    steps:
      - name: Show environment
        run: echo "Environment -> $APP_ENV"
    
  use-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Show support email
        run: echo "Support email -> ${{ vars.SUPPORT_EMAIL }}"

  use-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret key
        run: echo "Using secret key securely..."
        env:
          KEY: ${{ secrets.API_KEY }}